# File name: import.kv
<Import@BoxLayout>
	orientation: 'vertical'
	background_color: 0,0,1,1
	size_hint: (10, 1)
	Button:
		text: 'Import Song' 
	Button:
		text: 'Input Device'

	GridLayout:
		cols: 2
		spacing: 5
		anchor_x: 'right'
		anchor_y: 'bottom'
		BoxLayout: 
			orientation: 'vertical'
			Import:
				id: _import
				size_hint_x: .2
				size_hint_y: .2 
				height: self.parent.height * 0.111